const ZONAS = {
  'Apizaco': 'Apizaco Centro',
  'Tzompantepec': 'Cercana',
  'Santa Cruz Tlaxcala': 'Cercana',
  'Cuapiaxtla': 'Cercana',
  'Xaloztoc': 'Cercana',
  'Tocatlán': 'Cercana',
  'Tetla de la Solidaridad': 'Cercana',
  'San José Teacalco': 'Cercana',
  'Tlaxcala': 'Intermedia',
  'Ixtacuixtla de Mariano Matamoros': 'Intermedia',
  'Panotla': 'Intermedia',
  'Totolac': 'Intermedia',
  'Tepeyanco': 'Intermedia',
  'Santa Ana Nopalucan': 'Intermedia',
  'Santa Isabel Xiloxoxtla': 'Intermedia',
  'San Juan Huactzinco': 'Intermedia',
  'Yauhquemehcan': 'Intermedia',
  'Xaltocan': 'Intermedia',
  'San Lucas Tecopilco': 'Intermedia',
  'Atlangatepec': 'Intermedia',
  'Muñoz de Domingo Arenas': 'Intermedia',
  'Huamantla': 'Intermedia',
  'Atltzayanca': 'Intermedia',
  'Terrenate': 'Intermedia',
  'Cuaxomulco': 'Intermedia',
  'Contla de Juan Cuamatzi': 'Intermedia',
  'Chiautempan': 'Intermedia',
  'Apetatitlán de Antonio Carvajal': 'Intermedia',
  'Amaxac de Guerrero': 'Intermedia',
  'San Damián Texóloc': 'Intermedia',
  'San Francisco Tetlanohcan': 'Intermedia',
  'San Jerónimo Zacualpan': 'Intermedia',
  'San Lorenzo Axocomanitla': 'Intermedia',
  'Tepetitla de Lardizábal': 'Intermedia',
  'Nativitas': 'Intermedia',
  'Tetlatlahuca': 'Intermedia',
  'Zacatelco': 'Intermedia',
  'Santa Catarina Ayometla': 'Intermedia',
  'Xicohtzinco': 'Intermedia',
  'Papalotla de Xicohténcatl': 'Intermedia',
  'La Magdalena Tlaltelulco': 'Intermedia',
  'San Pablo del Monte': 'Intermedia',
  'Mazatecochco de José María Morelos': 'Intermedia',
  'Tenancingo': 'Intermedia',
  'Acuamanala de Miguel Hidalgo': 'Intermedia',
  'Santa Cruz Quilehtla': 'Intermedia',
  'Teolocholco': 'Intermedia',
  'Ixtenco': 'Intermedia',
  'Santa Apolonia Teacalco': 'Intermedia',
  'Calpulalpan': 'Lejana',
  'Nanacamilpa de Mariano Arista': 'Lejana',
  'Españita': 'Lejana',
  'Sanctórum de Lázaro Cárdenas': 'Lejana',
  'Benito Juárez': 'Lejana',
  'El Carmen Tequexquitla': 'Lejana',
  'Ziltlaltépec de Trinidad Sánchez Santos': 'Lejana',
  'Lázaro Cárdenas': 'Lejana',
  'Emiliano Zapata': 'Lejana',
  'Hueyotlipan': 'Lejana',
}

const PRECIOS = {
  'Apizaco Centro': 50,
  'Cercana': 80,
  'Intermedia': 100,
  'Lejana': 150,
}

console.log('Municipios clasificados:\n')
for (const [m, z] of Object.entries(ZONAS)) {
  console.log(`${m} → ${z} ($${PRECIOS[z]})`)
}
