export {
  variantesTelefono,
  jidToTelefono,
  extraerTelefono,
  obtenerClienteId,
  obtenerHistorial,
  obtenerUltimoMensaje,
  obtenerHistorialCompletoConTimestamp,
  agregarAlHistorial,
  obtenerMensajeId,
  marcarMensajeProcesado,
  yaProcesadoRecientemente,
  normalizarTexto,
  limpiarCachesConversacion,
  calcularHorasInactivo,
  detectarCambioTema,
  obtenerEstadoConversacion,
  CACHE_CLIENTE_UUID,
  MENSAJES_PROCESADOS,
  MAX_TURNOS_HISTORIAL,
  INACTIVIDAD_CAMBIO_TEMA_HR,
  INACTIVIDAD_ARCHIVAR_CASO_HR,
} from './conversation.service'
