export {
  crearCaso,
  obtenerCasoActivo,
  obtenerCasoPorId,
  buscarCasosPorTelefono,
  archivarCaso,
  reabrirCaso,
  actualizarActividad,
  actualizarTipoCaso,
  actualizarPrioridad,
  asociarPedido,
  asociarCotizacion,
  detectarCambioTema,
  clasificarTipoCaso,
  limpiarCachesCasos,
  cargarCasosDesdeBD,
} from './caso.service'
